runtime: python310
entry_point: hello_scheduled
is_public: false
schedule_config:
  cron: "0 2 * * *"
bucket_permissions:
  my-data-lake: roles/storage.objectViewer
secret_env_vars:
  API_KEY:
    secret_id: api-key
    version: "1"
